### ISSUE TITLE
Problem compiling erlware_commons

### ISSUE THREAD

**Issue by fuzzygroup** [keichan34/runroller#11]
Hi, 

I managed to get everything running on my local mac but when I tried on an ubuntu 14.04 box, I got this:

iex -S mix
Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [64-bit] [smp:24:24] [async-threads:10] [hipe] [kernel-poll:false]

==> erlware_commons (compile)
Compiled src/ec_dict.erl
Compiled src/ec_date.erl
src/ec_file.erl:177: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
src/ec_file.erl:178: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
Compiling src/ec_file.erl failed:
ERROR: compile failed while processing /home/banks/elixir/runroller/deps/erlware_commons: rebar_abort
*\* (Mix) Could not compile dependency :erlware_commons, "/home/banks/.mix/rebar compile skip_deps=true deps_dir="/home/banks/elixir/runroller/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile erlware_commons", update it with "mix deps.update erlware_commons" or clean it with "mix deps.clean erlware_commons"

Any suggestions?   I did a lot of googling and mucking about all to no avail.

**Comment by keichan34** [comment]
It seems like it's an incompatibility with Erlang/OTP 19. I'll push an updated version in a bit.
